AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DevX360 API (serverless, free-tier conscious)

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: Deployment stage name

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        NODE_ENV: !Ref StageName

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowOrigins:
          - http://localhost:3000
          - http://localhost:5500
          - http://localhost:5050

  # Main API Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: .
      Events:
        Proxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: "/{proxy+}"
            Method: ANY
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: "/"
            Method: ANY
      Environment:
        Variables:
          MONGODB_URI: "{{resolve:ssm:/devx360/api/MONGODB_URI}}"
          JWT_SECRET: "{{resolve:ssm:/devx360/api/JWT_SECRET}}"
          OPENAI_API_KEY: "{{resolve:ssm:/devx360/api/OPENAI_API_KEY}}"
          GITHUB_TOKEN_1: "{{resolve:ssm:/devx360/api/GITHUB_TOKEN_1}}"
          GITHUB_TOKEN_2: "{{resolve:ssm:/devx360/api/GITHUB_TOKEN_2}}"
          MCP_API_TOKEN: "{{resolve:ssm:/devx360/api/MCP_API_TOKEN}}"

  # Health Check Function (optional)
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: health.handler
      CodeUri: .
      Events:
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref ApiGateway
            Path: "/health"
            Method: GET

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"
  
  ApiId:
    Description: "API Gateway ID"
    Value: !Ref ApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-ApiId"