name: Frontend CI

on:
  push:
    branches:
      - feature/frontend
      - feature/documentation
      - main
  pull_request:
    branches:
      - feature/frontend
      - feature/documentation
      - main
jobs:
  test:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        working-directory: ./devx360-react
        run: npm ci

      - name: Run frontend tests
        working-directory: ./devx360-react
        run: npm test -- src/__tests__
