name: CI - Feature Analysis Tests

on:
  push:
    branches:
      - feature/ai-analysis
      - feature/documentation
      - main
  pull_request:
    branches:
      - feature/ai-analysis
      - feature/documentation
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:                        # <-- make sure this is aligned under the job
      OPENAI_API_KEY: ${{ secrets.OPENAI }}
    steps:
      - name: Checkout feature branch code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
