name: CI - Feature Analysis Tests

on:
  push:
    branches:
      - feature/ai-analysis
  pull_request:
    branches:
      - feature/ai-analysis

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI }}
    steps:
      - name: Checkout feature branch code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run passing unit tests
        run: |
          # Run only tests that previously passed
          npx jest "Data Collection/__tests__/**/*.test.js"
          npx jest "services/__tests__/**/*.test.js"
          npx jest "api/__tests__/auth.test.js"
          npx jest "api/__tests__/User.test.js"
          npx jest "api/__tests__/Team.test.js"
          npx jest "api/__tests__/RepoMetrics.test.js"
          npx jest "api/__tests__/concurrentMap.test.js"
