name: CI - Run Safe Tests (AI Analysis Feature)

on:
  push:
    branches:
      - 'feature/ai-analysis'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Run all safe tests
      run: |
        # Run tests excluding MongoDB-dependent and ESM-only suites
        npx jest \
          Data\ Collection/__tests__/universal-dora-service.test.js \
          Data\ Collection/__tests__/repository-info-service.test.js \
          Data\ Collection/__tests__/deployment-frequency.test.js \
          Data\ Collection/__tests__/parse-url.test.js \
          services/__tests__/codeInterpretor.test.js \
          services/__tests__/metricsService.test.js \
          services/__tests__/analysisService.test.js \
          services/__tests__/helpers.test.js \
          services/__tests__/tokenManager.test.js \
          api/__tests__/server.test.js \
          api/__tests__/auth.test.js \
          api/__tests__/Team.test.js \
          api/__tests__/User.test.js \
          api/__tests__/teams.endpoint.freq.test.js \
          api/__tests__/RepoMetrics.test.js \
          api/__tests__/concurrentMap.test.js \
          --runInBand \
          --silent
